# Generated by Django 3.2 on 2022-04-25 02:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=512)),
                ('Detail', models.CharField(max_length=2048)),
                ('Available', models.BooleanField(default=False)),
                ('Price', models.FloatField()),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ProductImages')),
            ],
        ),
    ]
