# Generated by Django 3.2 on 2022-05-03 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
