# Generated by Django 3.2 on 2022-05-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220504_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Recommended',
            field=models.BooleanField(default=False),
        ),
    ]
