# Generated by Django 3.2 on 2022-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220507_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='Titre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
