# Generated by Django 3.2 on 2022-05-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.CharField(default='.', max_length=512),
        ),
        migrations.AddField(
            model_name='member',
            name='Password',
            field=models.CharField(default='.', max_length=512),
            preserve_default=False,
        ),
    ]
