# Generated by Django 3.2 on 2022-05-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20220504_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_Name',
            field=models.CharField(max_length=512),
        ),
    ]
