# Generated by Django 3.2 on 2022-05-08 12:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Biceps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme_Name', models.CharField(max_length=512)),
                ('Programme_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Shoulders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
        migrations.CreateModel(
            name='Triceps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Name', models.CharField(max_length=512)),
                ('Repetition', models.CharField(max_length=512)),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ExercisesImages')),
            ],
        ),
    ]
