# Generated by Django 3.2 on 2022-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='Image_Link',
            field=models.CharField(default=False, max_length=512),
        ),
    ]
